### ISSUE TITLE
Login information required for zip file download

### ISSUE THREAD

**Issue by marcelluskoenig** [czarmanu/sentinel_lakeice#2]
Hi there,

I am working on a similar topic dealing with lakes in Germany and would like to test your model on our data.
To check that everything is up and running I would like reproduce your results first but when I try to download the sar_ice.zip file I am asked to enter username + password for your polybox server. Can you help me out here?

Many thanks and best regards,
Marcel

**Comment by czarmanu** [comment]
Hi Marcel,

Thanks for your interest in our work.

We are still not sure that we can share the data from GEE, that's why we introduced a password for the data. We have written to GEE but hasn't got any reply yet. So, until we get a positive reply, we will not be sharing the data. But, feel free to use our pre-trained model.

A way around this problem (not the best solution and we know it) is to download the data from GEE platform yourself.

Let us know if you have any doubts/questions.

best regards,
Manu

**Comment by marcelluskoenig** [comment]
Hi Manu,

 

thanks a lot for the fast reply : )

 

Okay, I understand your concerns.

I am going to try your pre-trained model.

 

Also, thanks a lot for your kind offer – I am quite sure that I will come back to you with some questions in the near future ; )

 

Best,

Marcel

 

Marcel König, M.Sc.

EOM PhD Candidate

+49 (0) 431 880-5642

 <mailto:koenig@geographie.uni-kiel.de> koenig@geographie.uni-kiel.de

____________________________________________________________________________

 



Earth Observation and Modelling

Kiel University

Department of Geography

Ludewig-Meyn-Str. 14

24098 Kiel

Germany

www.eom.uni-kiel.de <http://www.eom-group.de/> 

 

Von: Manu Tom <notifications@github.com> 
Gesendet: Freitag, 11. September 2020 10:49
An: czarmanu/sentinel_lakeice <sentinel_lakeice@noreply.github.com>
Cc: marcelluskoenig <koenig@geographie.uni-kiel.de>; Author <author@noreply.github.com>
Betreff: Re: [czarmanu/sentinel_lakeice] Login information required for zip file download (#2)

 

Hi Marcel,

Thanks for your interest in our work.

We are still not sure that we can share the data from GEE, that's why we introduced a password for the data. We have written to GEE but hasn't got any reply yet. So, until we get a positive reply, we will not be sharing the data. But, feel free to use our pre-trained model.

A way around this problem (not the best solution and we know it) is to download the data from GEE platform yourself.

Let us know if you have any doubts/questions.

best regards,
Manu
